### ISSUE TITLE
mv can't be used

### ISSUE THREAD

**Issue by Xuanwo** [qingstor/qsctl#244]
```
:) qsctl mv release qs://xuanwo-qsctl-test-1/test_mv/ -r
panic: Task ListDir value DirFunc is invalid

goroutine 1 [running]:
github.com/yunify/qsctl/v2/task.(*ListDirTask).validateInput(0xc000382580)
        github.com/yunify/qsctl/v2@/task/generated.go:1348 +0x288
github.com/yunify/qsctl/v2/task.(*ListDirTask).Run(0xc000382580)
        github.com/yunify/qsctl/v2@/task/generated.go:1373 +0x3d
github.com/yunify/qsctl/v2/pkg/schedule.(*RealScheduler).Sync(0xc0003140f0, 0xdf84a0, 0xc000382580)
        github.com/yunify/qsctl/v2@/pkg/schedule/scheduler.go:72 +0x9d
github.com/yunify/qsctl/v2/task.(*MoveDirTask).run(0xc0001f2a80)
        github.com/yunify/qsctl/v2@/task/move.go:20 +0x133
github.com/yunify/qsctl/v2/task.(*MoveDirTask).Run(0xc0001f2a80)
        github.com/yunify/qsctl/v2@/task/generated.go:1753 +0xc2
main.mvRun(0x125acc0, 0xc0002bf500, 0x2, 0x3, 0x0, 0x0)
        github.com/yunify/qsctl/v2@/cmd/qsctl/mv.go:59 +0x222
github.com/spf13/cobra.(*Command).execute(0x125acc0, 0xc0002bf470, 0x3, 0x3, 0x125acc0, 0xc0002bf470)
        github.com/spf13/cobra@v0.0.5/command.go:826 +0x524
github.com/spf13/cobra.(*Command).ExecuteC(0x125a540, 0xdf74a0, 0xc000021a40, 0xc000096010)
        github.com/spf13/cobra@v0.0.5/command.go:914 +0x41b
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        github.com/yunify/qsctl/v2@/cmd/qsctl/main.go:14 +0xf9

```

**Comment by Xuanwo** [comment]
Closed for fixed.
