### ISSUE TITLE
presign meet panic

### ISSUE THREAD

**Issue by Xuanwo** [qingstor/qsctl#245]
```
:) qsctl presign qs://xuanwo-qsctl-test-1/test
panic: Task ReachFile value Reacher is invalid

goroutine 1 [running]:
github.com/yunify/qsctl/v2/task.(*ReachFileTask).validateInput(0xc0004ec900)
        github.com/yunify/qsctl/v2@/task/generated.go:1891 +0x1cf
github.com/yunify/qsctl/v2/task.(*ReachFileTask).Run(0xc0004ec900)
        github.com/yunify/qsctl/v2@/task/generated.go:1906 +0x3d
main.presignRun(0x125af40, 0xc00022b960, 0x1, 0x1, 0x0, 0x0)
        github.com/yunify/qsctl/v2@/cmd/qsctl/presign.go:45 +0x10a
github.com/spf13/cobra.(*Command).execute(0x125af40, 0xc00022b920, 0x1, 0x1, 0x125af40, 0xc00022b920)
        github.com/spf13/cobra@v0.0.5/command.go:826 +0x524
github.com/spf13/cobra.(*Command).ExecuteC(0x125a540, 0xdf74a0, 0xc0000c99a0, 0xc00008e010)
        github.com/spf13/cobra@v0.0.5/command.go:914 +0x41b
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        github.com/yunify/qsctl/v2@/cmd/qsctl/main.go:14 +0xf9
```

**Comment by Xuanwo** [comment]
Closed for fixed.
