### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by wangzw** [qingstor/qsctl#294]
Version 2.1.1-1

```
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc0000343e0, 0xffffffffffffffff)
	sync/waitgroup.go:74 +0x139
sync.(*WaitGroup).Done(...)
	sync/waitgroup.go:99
github.com/qingstor/qsctl/v2/cmd/qsctl/taskutils.WaitProgress()
	github.com/qingstor/qsctl/v2@/cmd/qsctl/taskutils/progress.go:142 +0x36
main.syncRun(0x1005260, 0xc0002aea40, 0x2, 0x2, 0x0, 0x0)
	github.com/qingstor/qsctl/v2@/cmd/qsctl/sync.go:93 +0x2d0
github.com/spf13/cobra.(*Command).execute(0x1005260, 0xc0002ae9e0, 0x2, 0x2, 0x1005260, 0xc0002ae9e0)
	github.com/spf13/cobra@v0.0.7/command.go:838 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x1005ce0, 0xbc9680, 0xc0002ba2a0, 0xc000076058)
	github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
	github.com/qingstor/qsctl/v2@/cmd/qsctl/main.go:14 +0x68
```

**Comment by Prnyself** [comment]
We've already located the bug. Did you execute `qsctl sync` with `--no-progress` flag?

**Comment by wangzw** [comment]
Simply run command `qctl sync /dir qs://bucket/path`

**Comment by Prnyself** [comment]
> Simply run command `qctl sync /dir qs://bucket/path`

OK, we will fix this, release a new version and notify as soon as possible.

**Comment by Prnyself** [comment]
> Simply run command `qsctl sync /dir qs://bucket/path`

A commit has been pushed into master branch, is it convenient for you to build a binary file from master branch by `make build`?
